<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tyson Biegler. Student ID: 012170282">

<title>D212 Task 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Performance Assessment D212_files/libs/clipboard/clipboard.min.js"></script>
<script src="Performance Assessment D212_files/libs/quarto-html/quarto.js"></script>
<script src="Performance Assessment D212_files/libs/quarto-html/popper.min.js"></script>
<script src="Performance Assessment D212_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Performance Assessment D212_files/libs/quarto-html/anchor.min.js"></script>
<link href="Performance Assessment D212_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Performance Assessment D212_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Performance Assessment D212_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Performance Assessment D212_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Performance Assessment D212_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">D212 Task 3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tyson Biegler. Student ID: 012170282 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="part-i-research-question" class="level2">
<h2 class="anchored" data-anchor-id="part-i-research-question"><strong>Part I: Research Question</strong></h2>
<p><strong>A1:</strong> What are the most commonly co-prescribed medications, and are there any strong association rules that suggest patterns in prescription behavior?</p>
<p><strong>A2:</strong> My goal is to identify common medication combinations using market basket analysis, providing insights into prescription patters that can help executives better understand patient prescriptions.</p>
</section>
<section id="part-ii-market-basket-justification" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-market-basket-justification"><strong>Part II: Market Basket Justification</strong></h2>
<p><strong>B1:</strong> Market basket analysis finds patterns in the data by identifying frequently co-occurring variables, prescription in this case. In this case I am using the apriori algorithm which finds combinations of medications that are often prescribed together. As a result, the apriori algorithm will return the Support, Confidence, and Lift that I will explain in a later section.</p>
<p>After running market basket analysis using the apriori algorithm on this data I expect to see the following outcomes:</p>
<ol type="1">
<li><p>Groups of prescription that are frequently paired together.</p></li>
<li><p>The support value indicating the rate that these prescription combinations happen together.</p></li>
<li><p>Confidence values that determine the likelihood that groups will be prescribed together.</p></li>
<li><p>Lift, to determine if the prescriptions that are prescribed together is more likely than by chance alone.</p></li>
</ol>
<p><strong>B2:</strong> Not all transactions included any prescriptions. The following prescriptions are included in the second transaction. The first transaction did not include any prescriptions.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "abilify"                 "albuterol aerosol"      
 [3] "allopurinol"             "amlodipine"             
 [5] "cialis"                  "fluconozole"            
 [7] "gabapentin"              "lorazepam"              
 [9] "losartan"                "metoprolol succinate XL"
[11] "mometasone"              "omeprazole"             
[13] "pantoprazole"            "pravastatin"            
[15] "sulfamethoxazole"       </code></pre>
</div>
</div>
<p>Displayed below is a sample of the second transaction. The full transaction is very large so I included the first six values.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          abilify     acetaminophen           actonel albuterol aerosol 
             TRUE             FALSE             FALSE              TRUE 
    albuterol HFA       alendronate 
            FALSE             FALSE </code></pre>
</div>
</div>
<p><strong>B3:</strong> One main assumption of market basket analysis is that certain products, prescriptions in this case, tend to appear together in multiple transactions more often than expected by chance. This implies that there is a consistent occurrence of two or more prescriptions across numerous baskets. In the context of this medical data the assumption is that specific medications are frequently prescribed together, indicating possible relationships or patters, or just common treatment combinations.</p>
</section>
<section id="part-iii-data-preparation-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="part-iii-data-preparation-and-analysis"><strong>Part III: Data Preparation and Analysis</strong></h2>
<p><strong>C1:</strong> I will provide a cleaned csv file called ’’<em>cleaned_basket.csv</em>” in the assessment submission.</p>
<p><strong>C2:</strong> The following is the apriori algorithm code without errors. At the end of this code I print the line “Code ran successfully without errors” to demonstrate that there were no prior errors in the code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Analysis ----------------------------------------------------------------</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>arules <span class="ot">&lt;-</span> <span class="fu">apriori</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  basket, </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">list</span>(<span class="at">verbose =</span> <span class="cn">FALSE</span>), </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameter =</span> <span class="fu">list</span>(<span class="at">supp =</span> <span class="fl">0.008</span>, <span class="at">conf =</span> <span class="fl">0.4</span>, <span class="at">minlen =</span> <span class="dv">2</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">appearance =</span> <span class="fu">list</span>(<span class="at">rhs =</span> <span class="st">"abilify"</span>, <span class="at">default =</span> <span class="st">"lhs"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>redundant_r <span class="ot">&lt;-</span> <span class="fu">is.redundant</span>(arules) <span class="co">#removing redundant rules</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>refined_arules <span class="ot">&lt;-</span> arules[<span class="sc">!</span>redundant_r]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(<span class="fu">sort</span>(refined_arules, <span class="at">by =</span> <span class="st">'lift'</span>, <span class="at">decreasing =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    lhs                         rhs       support     confidence coverage  
[1] {metformin}              =&gt; {abilify} 0.011531796 0.4564644  0.02526330
[2] {carvedilol, lisinopril} =&gt; {abilify} 0.008532196 0.4353741  0.01959739
[3] {glipizide}              =&gt; {abilify} 0.013731502 0.4178499  0.03286229
[4] {lisinopril}             =&gt; {abilify} 0.020463938 0.4165536  0.04912678
    lift     count
[1] 3.829910 173  
[2] 3.652955 128  
[3] 3.505920 206  
[4] 3.495043 307  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If this line runs then there were no previous errors</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Code ran successfully without errors."</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Code ran successfully without errors."</code></pre>
</div>
</div>
<p><strong>C3:</strong> All values for this association rules table are listed below. With the confidence set to 0.4, five rules are returned.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    lhs                         rhs       support     confidence coverage  
[1] {metformin}              =&gt; {abilify} 0.011531796 0.4564644  0.02526330
[2] {carvedilol, lisinopril} =&gt; {abilify} 0.008532196 0.4353741  0.01959739
[3] {glipizide}              =&gt; {abilify} 0.013731502 0.4178499  0.03286229
[4] {lisinopril}             =&gt; {abilify} 0.020463938 0.4165536  0.04912678
    lift     count
[1] 3.829910 173  
[2] 3.652955 128  
[3] 3.505920 206  
[4] 3.495043 307  </code></pre>
</div>
</div>
<p><strong>C4:</strong> The following are the first three rules from the association rules table that I will explain in more detail.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    lhs                         rhs       support     confidence coverage  
[1] {metformin}              =&gt; {abilify} 0.011531796 0.4564644  0.02526330
[2] {carvedilol, lisinopril} =&gt; {abilify} 0.008532196 0.4353741  0.01959739
[3] {glipizide}              =&gt; {abilify} 0.013731502 0.4178499  0.03286229
    lift     count
[1] 3.829910 173  
[2] 3.652955 128  
[3] 3.505920 206  </code></pre>
</div>
</div>
<p>In the first rule <code>{metformin} =&gt; {abilify}</code>, the support is 0.0115, meaning 1.15% of all transactions include both Metformin and Abilify. The lift value is 3.83, making this the strongest association in the table. A lift of 3.83 indicates that patients prescribed Metformin are 3.83 times more likely to also be prescribed Abilify compared to random chance. The confidence is 0.4565, meaning that when Metformin appears in a transaction, there is a 45.65% probability that Abilify is also present.</p>
<p>The second rule <code>{carvedilol, lisinopril} =&gt; {abilify}</code> has the lowest support (0.0085), indicating that 0.85% of all transactions contain carvedilol, lisinopril, and Abilify. The lift is 3.65, meaning patients prescribed both Carvedilol and Lisinopril are 3.65 times more likely to also be prescribed Abilify compared to random chance. The confidence is 0.4354, indicating that when Carvedilol and lisinopril appear in a transaction, there is a 43.54% chance that Abilify is also present.</p>
<p>The third rule <code>{glipizide} =&gt; {abilify}</code> has the highest support (0.0137), meaning 1.37% of transactions contain both glipizide and Abilify. The lift is 3.51, suggesting that patients prescribed glipizide are 3.51 times more likely to also be prescribed Abilify compared to random chance. The confidence is 0.4178, meaning there is a 41.78% probability that Abilify is included when glipizide is prescribed.</p>
</section>
<section id="part-iv-data-summary-and-implications" class="level2">
<h2 class="anchored" data-anchor-id="part-iv-data-summary-and-implications"><strong>Part IV: Data Summary and Implications</strong></h2>
<p><strong>D1:</strong> The highest support value among the top three rules was 0.0137 (1.37%), meaning that 1.37% of all transactions contained both glipizide and Abilify. Higher support values indicate more frequent prescribing patterns. The highest lift value was 3.83 for the rule <code>{metformin} =&gt; {abilify}</code>, meaning that patients prescribed Metformin were 3.83 times more likely to also be prescribed abilify compared to random chance. The highest confidence value was 0.4565 (45.65%), indicating that when Metformin was prescribed, there was a 45.65% probability that abilify was also included in the transaction.</p>
<p><strong>D2:</strong> There are many practical implications of this analysis, such as understanding commodities among diagnosis. For example according to drugs.com, Metformin is primarily used to manage diabetes ((Drugs.com, 2023a) where as Abilify is an antipychotic (Drugs.com, 2023b). This appears to suggest that a subset of patients with diabetes is also being treated for mental health issues. Additionally, if a pharmacy knows these associations they can better stock medications if they know that patients that are prescribed Abilify (the most common prescription in the dataset) have a 43.54% probability that they will also need Metformin.</p>
<p><strong>D3:</strong> Based on this analysis, the hospital executives should focus on medication management to ensure all frequently co-prescribed medications are available, assuming that this hospital chain provides the medications as well as prescribes them. Additionally, this information should be loaded into the electronic health record so that the health care providers can review common medication combinations and make more informed decisions.<br>
</p>
</section>
<section id="part-v-attachments" class="level2">
<h2 class="anchored" data-anchor-id="part-v-attachments"><strong>Part V: Attachments</strong></h2>
<p>E.&nbsp;&nbsp;The Panopto video link will be provided in the submission files.</p>
<p>F.&nbsp;Code sources:</p>
<ul>
<li>Kamara, K. (2022, August 28). Data mining II - D212 [Video]. Panopto. <a href="https://wgu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5674b196-a9f1-4e85-a322-af0000021f3f" class="uri">https://wgu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5674b196-a9f1-4e85-a322-af0000021f3f</a><br>
</li>
</ul>
<p>G. In text sources:</p>
<ul>
<li><p>Drugs.com. (2023a, August 22). Metformin: Uses, dosage, side effects, and warnings. <a href="https://www.drugs.com/metformin.html" class="uri">https://www.drugs.com/metformin.html</a></p></li>
<li><p>Drugs.com. (2023b, August 22). Abilify: Uses, dosage, side effects, and warnings. <a href="https://www.drugs.com/abilify.html" class="uri">https://www.drugs.com/abilify.html</a></p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>