<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tyson Biegler">

<title>Advanced Data Analytics - D213 Task 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="D213 Task 1 Write up_files/libs/clipboard/clipboard.min.js"></script>
<script src="D213 Task 1 Write up_files/libs/quarto-html/quarto.js"></script>
<script src="D213 Task 1 Write up_files/libs/quarto-html/popper.min.js"></script>
<script src="D213 Task 1 Write up_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="D213 Task 1 Write up_files/libs/quarto-html/anchor.min.js"></script>
<link href="D213 Task 1 Write up_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="D213 Task 1 Write up_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="D213 Task 1 Write up_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="D213 Task 1 Write up_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="D213 Task 1 Write up_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Advanced Data Analytics - D213 Task 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tyson Biegler </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="part-i-research-question" class="level2">
<h2 class="anchored" data-anchor-id="part-i-research-question"><strong>Part I: Research Question</strong></h2>
<p>A1. Can the ARIMA model effectively forecast 180 days of telecom revenue data with high accuracy?</p>
<p>A2. The main purpose of this assessment is to evaluate the ARIMA model’s ability to accurately forecast 180 days of revenue data. The objective is to assess the model’s performance by comparing its forecasts to the actual observed revenue values from the test data.</p>
</section>
<section id="part-ii-method-justification" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-method-justification"><strong>Part II: Method Justification</strong></h2>
<p>B1. Time series models assume that the data is stationary (GeeksforGeeks, 2024), meaning that the mean and variance remain constant over time. Additionally, time series models typicaly rely on autocorrelation, where past values influence current ones. This is important because models like ARIMA leverage this correlation to identify patterns over time, enabling accurate forecast pred</p>
</section>
<section id="part-iii-data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="part-iii-data-preparation"><strong>Part III: Data Preparation</strong></h2>
<p>C1. The time series plot shows a clear upward trend over the years. There appears to be some variability along the way without any imediate signs of patters or seasonality. These will be investigated further later.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>C2. The time step formatting required that the days be converted into a proper date format. In this time series model I chose to start the date on 2023-01-01 and ending on 2024-12-31 as shown in the code <code>range(data$Day)</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2023-01-01" "2024-12-31"</code></pre>
</div>
</div>
<p>This formatting uses daily intervals to ensure a regular time step without any gaps. However, to ensure that there were no gaps, I ran <code>any(is.na(data))</code> and <code>length(data$Day)</code>. Lastly the data is converted into a time series object with a yearly frequency of 365 observations per year.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>There are 731 rows of data.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Missing values: FALSE</code></pre>
</div>
</div>
<p>C3. I checked stationarity using the Augmented Dickey-Fuller (ADF) test. Initially the test returned a p-value of 0.02431 when ran on the original data. A p-value of this size suggests that the data is stationary (StatisticsHowTo, n.d.). However, there is a visible trend in the data.</p>
<p>The <code>ndiffs()</code> function suggests that time series data needs differencing. I differenced the data and accounted for seasonality (<code>DY &lt;- diff(Y, s = 1)</code>) and ran ADF on the differenced data. The new p-value shows improved stationarity and a more significant result at .01 as well as removal of the trend.</p>
<p>The seasonal differencecing accounts for the yearly seasonality that appears to occur once a year. I will explain more about this in the coming sections.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Y
Dickey-Fuller = -3.6938, Lag order = 9, p-value = 0.02431
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Recomended number of differencing: 1</code></pre>
</div>
</div>
<p>After differencing the time series data (Y):</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  DY
Dickey-Fuller = -8.6354, Lag order = 8, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>C4.&nbsp; In order to prepare the data, I started by loading the libraries (<code>tidyverse</code> , <code>forecast</code> , <code>tseries</code>) and then I converted the data into a time series format noting the daily nature of the data with <code>frequency=365</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#converting to ts</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">ts</span>(data<span class="sc">$</span>Revenue, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2023</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">365</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I checked for missing values to ensure there were no gaps in the data, and then plotted the data to visualize trends and any fluctuations.</p>
<p>Before exporting the cleaned data, I split the data into a train and test set, 80/20 split. I allocated the first 80% of the data to the training set, and the remaining 20% to the test set.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>C5.&nbsp;&nbsp;A copy of the cleaned csv file will be included in the submission files. The cleaned csv file is named <code>cleaned_ts_data.csv</code></p>
</section>
<section id="part-iv-model-identification-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="part-iv-model-identification-and-analysis"><strong>Part IV: Model Identification and Analysis</strong></h2>
<p>D1. The seasonality component shows and IQR accounting for 29.1% of the total IQR meaning that the seasonal fluctuations have an impact on the variability of the data. This seasonality can also be seen in the plot below.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Call:
 stl(x = Y, s.window = "periodic", t.window = 365, robust = TRUE)

 Time.series components:
    seasonal              trend             remainder        
 Min.   :-2.1803841   Min.   : 2.043455   Min.   :-6.723049  
 1st Qu.:-0.8099809   1st Qu.: 6.963760   1st Qu.:-0.661487  
 Median :-0.1907993   Median :10.690851   Median : 0.032188  
 Mean   : 0.0009227   Mean   : 9.953382   Mean   :-0.131404  
 3rd Qu.: 0.8467831   3rd Qu.:13.107337   3rd Qu.: 0.670740  
 Max.   : 2.7027377   Max.   :15.837858   Max.   : 3.898453  
 IQR:
     STL.seasonal STL.trend STL.remainder data 
     1.657        6.144     1.332         5.694
   %  29.1        107.9      23.4         100.0

 Weights:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.8739  0.9452  0.8865  0.9871  1.0000 

 Other components: List of 5
 $ win  : Named num [1:3] 7311 365 365
 $ deg  : Named int [1:3] 0 1 1
 $ jump : Named num [1:3] 732 37 37
 $ inner: int 1
 $ outer: int 15</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In addition, the spectral density plot shows that the highest spectral density happens at the lower end of the frequencies, suggesting a long term seasonality.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="trend" class="level4">
<h4 class="anchored" data-anchor-id="trend">Trend</h4>
<p>The decomposed time series plot shows a clean upward trend. The data begins in 2023 and gradually increases through 2025.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  2.043   6.964  10.691   9.953  13.107  15.838 </code></pre>
</div>
</div>
</section>
<section id="acf" class="level4">
<h4 class="anchored" data-anchor-id="acf">ACF</h4>
<p>In the Autocorrelation (ACF) plot of the differenced data, it appears that most values fall within the confidence lines. However, there are several lines that do pass the confidence lines indicating that there may be seasonality, or at least a strong relationship witht the previous lag. Seasonality can be examined further in the decomposition plot using <code>stl()</code>. This plot also shows a significant correlation at lag 2 and then tappers off, indicating an <code>AR(2)</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="pacf" class="level4">
<h4 class="anchored" data-anchor-id="pacf">PACF</h4>
<p>The Partial Autocorrelation (PACF) plot of the differenced data, looks very similar to the ACF plot where most of the values fall within the confidence interval lines. This would suggest that there is minimal partial autocorrelation at most lags. This plot shows a clear spike at lag 1 and then tappers off, indicating an <code>AR(1)</code>. Because PACF better isolates the relationship at each lag, I will be interested in an ARMIA model with an <code>AR(1)</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The decomposed time series plot shows several of the components already spoken about in previous sections, in addition to the remainder component. In essence, decomposition is the break down of the data set into its key components. The remainder component being the only one not yet spoken about explicitly, explains the portion of the data that can not be explained by the seasonal or tend components. In otherwords, the elements within this remainder component are the ones that do not follow a consistent trend or cyclical pattern (seasonality).</p>
<p>In this plot we can see that the remainder fluctuates around 0 with minor ups and downs. However, near the end of 2024 we can see a significant dip in the remainder that would suggest that during this period, an external or random event happened that affected the data which is why it wouldn’t be captured by the trend or seasonality in the data.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <strong>Ljung-box test</strong>, tests the if the residuals show any autocorrelation. with a p-value far less than 0.05 (&lt;2.2e-16) at lag 1, I can assume that there is some pattern or dependence that is not fully explained by the seasonality or trend mentioned earlier.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  decomposed$time.series[, "remainder"]
X-squared = 644.82, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To confirm the residuals (remainder) do not have a trend, I computed the ADF once again but this time on the remainder component. We can see that the p-value (<code>p-value=0.01</code>) is less than the standard significance level of 0.05. While the data, statistically, appears to be stationary, the Ljung-box test would still indicate that there might still be some predictable relationship between the lags.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  decomposed$time.series[, "remainder"]
Dickey-Fuller = -4.0837, Lag order = 9, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
</div>
<p>The ACF of the residuals plot shows that several peaks that are outside the confidence intervals. This means that the some patters or dependancy still exists in the data.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>However, when looking at the PACF we can see that only lags 1 and 2 have a direct significant influence on the remainder component. After lag 2 all the spikes fall within the confidence interval and the spikes get smaller overtime. While the ACF plot suggests that there is autocorrelation at many different lags, the PACF plot clarifies that the patterns seen in the ACF are likely indirect relationships that stem from the first 2 lags.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Decomposed Time Series</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>D2. I used <code>auto.arima()</code> to find the best ARIMA model. <code>d=1</code> tells ARIMAto take the difference of the data before it fits the data. <code>D=1</code> accounts for seasonality. <code>Stepwise=FALSE</code> trys all models to get the most accurate results. And lastly, <code>approximation=FALSE</code> ensures that the <code>AIC</code> values are not approximated. Run time was not an issue here so I set approximation to false (RDocumentation, n.d.).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fit_arima <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(train, <span class="at">d=</span><span class="dv">1</span>, <span class="at">D=</span><span class="dv">1</span>, <span class="at">stepwise =</span> <span class="cn">FALSE</span>, <span class="at">approximation =</span> <span class="cn">FALSE</span>, <span class="at">trace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ARIMA(0,1,0)                    : 909.2825
 ARIMA(0,1,0) with drift         : 910.1682
 ARIMA(0,1,1)                    : 800.4773
 ARIMA(0,1,1) with drift         : 798.946
 ARIMA(0,1,2)                    : 776.4192
 ARIMA(0,1,2) with drift         : 776.048
 ARIMA(0,1,3)                    : 775.7495
 ARIMA(0,1,3) with drift         : 775.0052
 ARIMA(0,1,4)                    : 777.7842
 ARIMA(0,1,4) with drift         : 777.0359
 ARIMA(0,1,5)                    : 779.7498
 ARIMA(0,1,5) with drift         : 779.0592
 ARIMA(1,1,0)                    : 774.056
 ARIMA(1,1,0) with drift         : 773.0878
 ARIMA(1,1,1)                    : 776.0741
 ARIMA(1,1,1) with drift         : 775.1125
 ARIMA(1,1,2)                    : 776.0088
 ARIMA(1,1,2) with drift         : 775.4037
 ARIMA(1,1,3)                    : 777.7843
 ARIMA(1,1,3) with drift         : 777.0377
 ARIMA(1,1,4)                    : Inf
 ARIMA(1,1,4) with drift         : 779.0796
 ARIMA(2,1,0)                    : 776.0734
 ARIMA(2,1,0) with drift         : 775.1118
 ARIMA(2,1,1)                    : 777.6634
 ARIMA(2,1,1) with drift         : 776.6363
 ARIMA(2,1,2)                    : 777.7935
 ARIMA(2,1,2) with drift         : 777.1338
 ARIMA(2,1,3)                    : 779.86
 ARIMA(2,1,3) with drift         : 779.1622
 ARIMA(3,1,0)                    : 775.885
 ARIMA(3,1,0) with drift         : 775.2674
 ARIMA(3,1,1)                    : 777.8984
 ARIMA(3,1,1) with drift         : 777.2592
 ARIMA(3,1,2)                    : 779.8004
 ARIMA(3,1,2) with drift         : 779.1123
 ARIMA(4,1,0)                    : 777.8895
 ARIMA(4,1,0) with drift         : 777.2283
 ARIMA(4,1,1)                    : Inf
 ARIMA(4,1,1) with drift         : Inf
 ARIMA(5,1,0)                    : 779.846
 ARIMA(5,1,0) with drift         : 779.1125



 Best model: ARIMA(1,1,0) with drift         </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#accounting for trend with d=1. Tells arima that before it fits the data, take the difference of the data</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">#accounting for seasonality with D=1. Gets rid of the seasonality by taking the first seasonal difference</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co">#stepwise=FALSE trying all models to get the most accurate results</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#approximation=FALSE because time isnt an issue. If it were an issue thenapproximation could be set to TRUE but it would come at the cost of approximated AIC values.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see that the best model, according the auto.arima() is <code>ARIMA(1,1,0) with drift</code> (accounting for the trend).</p>
<p>The model summary shows that the <code>AR(1)</code> that was mentioned in the D1 as a result of the PACF test was accurate. ‘I’, shows that difference has been applied, and ‘0’ indicates that there is no moving average in this model.</p>
<p>D3.&nbsp;The following plot shows the forecast with confidence intervals for 90 days in advance.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>D4.&nbsp;In the following code output, you can see the daily values for 90 days as well as the upper and lower confidence values.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Forecast method: ARIMA(1,1,0) with drift

Model Information:
Series: train 
ARIMA(1,1,0) with drift 

Coefficients:
          ar1   drift
      -0.4605  0.0230
s.e.   0.0367  0.0133

sigma^2 = 0.2189:  log likelihood = -383.52
AIC=773.05   AICc=773.09   BIC=786.15

Error measures:
                        ME      RMSE       MAE  MPE MAPE      MASE         ACF1
Training set -1.354846e-05 0.4666594 0.3758019 -Inf  Inf 0.8756595 -0.001967013

Forecasts:
    Point Forecast    Lo 80    Hi 80     Lo 95    Hi 95
585       13.34397 12.74438 13.94356 12.426978 14.26097
586       13.45161 12.77033 14.13289 12.409682 14.49354
587       13.43558 12.61875 14.25240 12.186346 14.68481
588       13.47649 12.57044 14.38254 12.090810 14.86218
589       13.49118 12.49293 14.48944 11.964482 15.01789
590       13.51795 12.44006 14.59585 11.869456 15.16645
591       13.53916 12.38509 14.69323 11.774162 15.30416
592       13.56293 12.33829 14.78757 11.690008 15.43585
593       13.58552 12.29378 14.87726 11.609975 15.56106
594       13.60865 12.25330 14.96400 11.535816 15.68148
595       13.63153 12.21534 15.04772 11.465660 15.79740
596       13.65453 12.18005 15.12901 11.399505 15.90955
597       13.67747 12.14690 15.20804 11.336667 16.01828
598       13.70044 12.11577 15.28511 11.276898 16.12398
599       13.72340 12.08641 15.36038 11.219846 16.22695
600       13.74636 12.05868 15.43404 11.165280 16.32744
601       13.76932 12.03243 15.50621 11.112973 16.42567
602       13.79228 12.00753 15.57703 11.062742 16.52182
603       13.81524 11.98388 15.64660 11.014422 16.61606
604       13.83820 11.96139 15.71501 10.967873 16.70853
605       13.86116 11.93998 15.78235 10.922967 16.79936
606       13.88412 11.91957 15.84868 10.879593 16.88866
607       13.90708 11.90009 15.91408 10.837653 16.97652
608       13.93005 11.88149 15.97860 10.797057 17.06303
609       13.95301 11.86372 16.04229 10.757725 17.14829
610       13.97597 11.84673 16.10520 10.719585 17.23235
611       13.99893 11.83048 16.16738 10.682570 17.31529
612       14.02189 11.81492 16.22886 10.646620 17.39716
613       14.04485 11.80002 16.28968 10.611681 17.47802
614       14.06781 11.78575 16.34987 10.577703 17.55792
615       14.09077 11.77208 16.40946 10.544639 17.63690
616       14.11373 11.75898 16.46849 10.512446 17.71502
617       14.13669 11.74642 16.52696 10.481085 17.79230
618       14.15965 11.73438 16.58492 10.450520 17.86879
619       14.18261 11.72284 16.64239 10.420716 17.94451
620       14.20557 11.71178 16.69937 10.391642 18.01951
621       14.22853 11.70117 16.75590 10.363269 18.09380
622       14.25150 11.69101 16.81198 10.335568 18.16742
623       14.27446 11.68127 16.86765 10.308515 18.24040
624       14.29742 11.67193 16.92290 10.282084 18.31275
625       14.32038 11.66299 16.97777 10.256254 18.38450
626       14.34334 11.65443 17.03225 10.231003 18.45567
627       14.36630 11.64623 17.08637 10.206310 18.52629
628       14.38926 11.63838 17.14014 10.182157 18.59636
629       14.41222 11.63088 17.19356 10.158525 18.66592
630       14.43518 11.62370 17.24666 10.135399 18.73496
631       14.45814 11.61685 17.29943 10.112761 18.80352
632       14.48110 11.61031 17.35190 10.090597 18.87161
633       14.50406 11.60406 17.40407 10.068892 18.93923
634       14.52702 11.59811 17.45594 10.047633 19.00642
635       14.54998 11.59244 17.50753 10.026805 19.07316
636       14.57295 11.58704 17.55885 10.006398 19.13949
637       14.59591 11.58191 17.60990  9.986398 19.20541
638       14.61887 11.57704 17.66069  9.966796 19.27094
639       14.64183 11.57242 17.71123  9.947579 19.33608
640       14.66479 11.56805 17.76153  9.928738 19.40084
641       14.68775 11.56392 17.81158  9.910262 19.46524
642       14.71071 11.56002 17.86140  9.892143 19.52928
643       14.73367 11.55635 17.91100  9.874371 19.59297
644       14.75663 11.55289 17.96037  9.856938 19.65633
645       14.77959 11.54966 18.00953  9.839835 19.71935
646       14.80255 11.54663 18.05847  9.823054 19.78205
647       14.82551 11.54381 18.10721  9.806588 19.84444
648       14.84847 11.54120 18.15575  9.790429 19.90652
649       14.87143 11.53877 18.20410  9.774571 19.96830
650       14.89440 11.53654 18.25225  9.759006 20.02979
651       14.91736 11.53450 18.30021  9.743728 20.09098
652       14.94032 11.53264 18.34799  9.728730 20.15190
653       14.96328 11.53096 18.39559  9.714007 20.21255
654       14.98624 11.52946 18.44302  9.699552 20.27292
655       15.00920 11.52813 18.49027  9.685361 20.33304
656       15.03216 11.52696 18.53735  9.671427 20.39289
657       15.05512 11.52597 18.58427  9.657745 20.45250
658       15.07808 11.52513 18.63103  9.644310 20.51185
659       15.10104 11.52445 18.67763  9.631117 20.57097
660       15.12400 11.52393 18.72408  9.618162 20.62984
661       15.14696 11.52356 18.77037  9.605440 20.68849
662       15.16992 11.52333 18.81651  9.592946 20.74690
663       15.19288 11.52326 18.86251  9.580675 20.80509
664       15.21585 11.52333 18.90836  9.568625 20.86307
665       15.23881 11.52354 18.95408  9.556790 20.92082
666       15.26177 11.52388 18.99965  9.545167 20.97837
667       15.28473 11.52437 19.04509  9.533753 21.03570
668       15.30769 11.52498 19.09039  9.522542 21.09283
669       15.33065 11.52573 19.13557  9.511532 21.14977
670       15.35361 11.52661 19.18061  9.500719 21.20650
671       15.37657 11.52761 19.22553  9.490100 21.26304
672       15.39953 11.52874 19.27032  9.479671 21.31939
673       15.42249 11.52999 19.31499  9.469430 21.37555
674       15.44545 11.53137 19.35954  9.459373 21.43153
675       15.46841 11.53286 19.40397  9.449497 21.48733
676       15.49137 11.53446 19.44829  9.439799 21.54295
677       15.51433 11.53618 19.49249  9.430276 21.59839
678       15.53730 11.53802 19.53657  9.420926 21.65366
679       15.56026 11.53996 19.58055  9.411746 21.70877
680       15.58322 11.54202 19.62442  9.402733 21.76370
681       15.60618 11.54418 19.66818  9.393885 21.81847
682       15.62914 11.54645 19.71183  9.385198 21.87308
683       15.65210 11.54882 19.75538  9.376671 21.92753
684       15.67506 11.55129 19.79883  9.368301 21.98182
685       15.69802 11.55387 19.84217  9.360087 22.03595
686       15.72098 11.55654 19.88542  9.352024 22.08994
687       15.74394 11.55932 19.92857  9.344113 22.14377
688       15.76690 11.56219 19.97162  9.336349 22.19746
689       15.78986 11.56516 20.01457  9.328731 22.25100
690       15.81282 11.56822 20.05743  9.321258 22.30439
691       15.83578 11.57137 20.10020  9.313926 22.35764
692       15.85875 11.57462 20.14287  9.306735 22.41076
693       15.88171 11.57795 20.18546  9.299682 22.46373
694       15.90467 11.58138 20.22796  9.292765 22.51657
695       15.92763 11.58489 20.27037  9.285982 22.56927
696       15.95059 11.58849 20.31269  9.279332 22.62184
697       15.97355 11.59217 20.35493  9.272813 22.67429
698       15.99651 11.59594 20.39708  9.266423 22.72660
699       16.01947 11.59979 20.43915  9.260160 22.77878
700       16.04243 11.60373 20.48113  9.254023 22.83084
701       16.06539 11.60775 20.52304  9.248011 22.88277
702       16.08835 11.61184 20.56486  9.242121 22.93458
703       16.11131 11.61602 20.60661  9.236352 22.98628
704       16.13427 11.62027 20.64828  9.230702 23.03785
705       16.15723 11.62460 20.68987  9.225171 23.08930
706       16.18020 11.62901 20.73138  9.219756 23.14063
707       16.20316 11.63349 20.77282  9.214457 23.19186
708       16.22612 11.63805 20.81419  9.209271 23.24296
709       16.24908 11.64268 20.85548  9.204198 23.29396
710       16.27204 11.64738 20.89670  9.199236 23.34484
711       16.29500 11.65216 20.93784  9.194384 23.39561
712       16.31796 11.65700 20.97892  9.189640 23.44628
713       16.34092 11.66192 21.01992  9.185003 23.49684
714       16.36388 11.66690 21.06086  9.180473 23.54729
715       16.38684 11.67196 21.10173  9.176047 23.59764
716       16.40980 11.67708 21.14253  9.171725 23.64788
717       16.43276 11.68227 21.18326  9.167506 23.69802
718       16.45572 11.68752 21.22393  9.163387 23.74806
719       16.47868 11.69284 21.26453  9.159369 23.79800
720       16.50165 11.69823 21.30506  9.155450 23.84784
721       16.52461 11.70368 21.34554  9.151629 23.89758
722       16.54757 11.70919 21.38595  9.147905 23.94723
723       16.57053 11.71476 21.42629  9.144277 23.99678
724       16.59349 11.72040 21.46658  9.140744 24.04623
725       16.61645 11.72610 21.50680  9.137304 24.09559
726       16.63941 11.73186 21.54696  9.133957 24.14486
727       16.66237 11.73768 21.58706  9.130703 24.19404
728       16.68533 11.74356 21.62711  9.127539 24.24312
729       16.70829 11.74949 21.66709  9.124465 24.29212
730       16.73125 11.75549 21.70702  9.121480 24.34102
731       16.75421 11.76154 21.74688  9.118584 24.38984
732       16.77717 11.76765 21.78669  9.115774 24.43857
733       16.80013 11.77382 21.82645  9.113051 24.48722
734       16.82310 11.78004 21.86615  9.110414 24.53578
735       16.84606 11.78632 21.90579  9.107861 24.58425
736       16.86902 11.79266 21.94538  9.105392 24.63264
737       16.89198 11.79904 21.98491  9.103006 24.68095
738       16.91494 11.80548 22.02439  9.100703 24.72917
739       16.93790 11.81198 22.06382  9.098481 24.77732
740       16.96086 11.81853 22.10319  9.096339 24.82538
741       16.98382 11.82513 22.14252  9.094277 24.87336
742       17.00678 11.83178 22.18179  9.092295 24.92127
743       17.02974 11.83848 22.22100  9.090390 24.96909
744       17.05270 11.84523 22.26017  9.088564 25.01684
745       17.07566 11.85204 22.29929  9.086814 25.06451
746       17.09862 11.85889 22.33836  9.085141 25.11211
747       17.12158 11.86579 22.37738  9.083543 25.15963
748       17.14455 11.87274 22.41635  9.082019 25.20707
749       17.16751 11.87974 22.45527  9.080570 25.25444
750       17.19047 11.88679 22.49414  9.079195 25.30174
751       17.21343 11.89389 22.53297  9.077892 25.34896
752       17.23639 11.90103 22.57175  9.076661 25.39612
753       17.25935 11.90822 22.61048  9.075502 25.44320
754       17.28231 11.91545 22.64916  9.074414 25.49021
755       17.30527 11.92274 22.68780  9.073396 25.53715
756       17.32823 11.93006 22.72640  9.072447 25.58401
757       17.35119 11.93744 22.76495  9.071568 25.63082
758       17.37415 11.94485 22.80345  9.070757 25.67755
759       17.39711 11.95232 22.84191  9.070014 25.72421
760       17.42007 11.95982 22.88033  9.069338 25.77081
761       17.44303 11.96737 22.91870  9.068729 25.81734
762       17.46600 11.97496 22.95703  9.068186 25.86380
763       17.48896 11.98260 22.99531  9.067709 25.91020
764       17.51192 11.99028 23.03356  9.067297 25.95654</code></pre>
</div>
</div>
<p>D5. The full code file will be included in the submission files. The code file will be named <code>D213_code.R</code></p>
</section>
</section>
<section id="part-v-data-summary-and-implications" class="level2">
<h2 class="anchored" data-anchor-id="part-v-data-summary-and-implications"><strong>Part V: Data Summary and Implications</strong></h2>
<p>E1. As mentioned in section D2 the ARIMA model with the best fit is <code>ARIMA(1,1,0) with drift</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: train 
ARIMA(1,1,0) with drift 

Coefficients:
          ar1   drift
      -0.4605  0.0230
s.e.   0.0367  0.0133

sigma^2 = 0.2189:  log likelihood = -383.52
AIC=773.05   AICc=773.09   BIC=786.15

Training set error measures:
                        ME      RMSE       MAE  MPE MAPE      MASE         ACF1
Training set -1.354846e-05 0.4666594 0.3758019 -Inf  Inf 0.8756595 -0.001967013</code></pre>
</div>
</div>
<p>The predictions intervals are 80% (Lo), and 95%(Hi) for each forecast point. For example, at point 585, the forecast is 13.34397, with an 80% interval of 12.74438 on the low end and 13.94356 on the high end. Likewise, 95% interval of 12.426978 on the low end and 14.26097 on the high end. In other wards, for point 585, I can say that there is an 80% chance that the value is between 13.34397 and 12.74438. However, there is a 95% chance that the value is between 12.426978 and 14.26097 . So the higher the confidence, the wider the range because it is reflecting the greater uncertainty in the prediction.</p>
<p>The forecast length is 180 days worth of data because the data contains enough information to identify season trends or patterns.</p>
<p>The error metrics that are provided in the summary function include RMSE and MAE as well as others. To test how well the data forecasts the trained data, I will be comparing the test set vs the training set.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                        ME      RMSE       MAE       MPE     MAPE      MASE
Training set -1.354846e-05 0.4666594 0.3758019      -Inf      Inf 0.8756595
Test set     -1.432728e+00 2.2949433 1.8155156 -12.74361 15.11012 4.2303496
                     ACF1
Training set -0.001967013
Test set               NA</code></pre>
</div>
</div>
<p>This ARIMA model <code>(1,1,0)</code> appears to work well with the training data as indicated by the low <code>RMSE (0.4666594)</code>, <code>MASE (0.8756595)</code>, meaning that it first the historical data well. However, when tested on the unseen data, the model does not do as well. The errors <code>RMSE (2.2949433)</code>, and <code>MASE (4.2303496)</code> are much higher with the test data, and the model tends to underestimate the values as evidenced by the negative <code>ME (-1.432728e+00)</code>.</p>
<p>E2.&nbsp;Annotated visual of the forecast and test data:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D213-Task-1-Write-up_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>E3. This model performs well with the historical data in that it can identify patters and trends accurately but seems to struggle with future data as it tends to underestimate the actual values. Because of this I would recommend that the company take into account the model’s tendency to under predict revenue and expect that the actual revenue will be someone higher. This could also imply that the demand is higher as well, and therefore the company should take this into account when allocating resources or esitimating inventory. Additionally I would recommend monittoring this model’s performance on a regular schedule to compare the actual and foretasted numbers.</p>
</section>
<section id="part-vi-reporting" class="level2">
<h2 class="anchored" data-anchor-id="part-vi-reporting"><strong>Part VI: Reporting</strong></h2>
<p>G-H.&nbsp;&nbsp;Acknowledge sources, using in-text citations and references, for content that is quoted, paraphrased, or summarized.</p>
<p>GeeksforGeeks. (2024, October 9). <em>Time series in R - Stationarity testing</em>. GeeksforGeeks. <a href="https://www.geeksforgeeks.org/time-series-in-r-stationarity-testing/" class="uri">https://www.geeksforgeeks.org/time-series-in-r-stationarity-testing/</a></p>
<p>RDocumentation. (n.d.). <em>auto.arima function – forecast package (version 8.16)</em>. <a href="https://www.rdocumentation.org/packages/forecast/versions/8.16/topics/auto.arima" class="uri">https://www.rdocumentation.org/packages/forecast/versions/8.16/topics/auto.arima</a></p>
<p>StatisticsHowTo. (n.d.). <em>ADF – Augmented Dickey-Fuller test</em>. StatisticsHowTo. <a href="https://www.statisticshowto.com/adf-augmented-dickey-fuller-test/" class="uri">https://www.statisticshowto.com/adf-augmented-dickey-fuller-test/</a></p>
<p>weecology. (2020, September 21). <em>Introduction to making forecasts from time-series models in R</em> [Video]. YouTube. <a href="https://www.youtube.com/watch?v=kyPg3jV4pJ8" class="uri">https://www.youtube.com/watch?v=kyPg3jV4pJ8</a></p>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>