<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tyson Biegler">

<title>D209 Task 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="D209_Task1_V1_WriteUp_files/libs/clipboard/clipboard.min.js"></script>
<script src="D209_Task1_V1_WriteUp_files/libs/quarto-html/quarto.js"></script>
<script src="D209_Task1_V1_WriteUp_files/libs/quarto-html/popper.min.js"></script>
<script src="D209_Task1_V1_WriteUp_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="D209_Task1_V1_WriteUp_files/libs/quarto-html/anchor.min.js"></script>
<link href="D209_Task1_V1_WriteUp_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="D209_Task1_V1_WriteUp_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="D209_Task1_V1_WriteUp_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="D209_Task1_V1_WriteUp_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="D209_Task1_V1_WriteUp_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">D209 Task 1</h1>
<p class="subtitle lead">Student ID: 012170282</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tyson Biegler </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="part-i-research-question" class="level1">
<h1><strong>Part I: Research Question</strong></h1>
<p><strong>A1.</strong>&nbsp;Can KNN determine which factors are most strongly associated with customer churn, and how accurately can it do so?<br>
<strong>A2.</strong>&nbsp;&nbsp;The goal is to use KNN to predict customer churn and discover how effective KNN is at predicting customer churn.</p>
</section>
<section id="part-ii-method-justification" class="level1">
<h1><strong>Part II: Method Justification</strong></h1>
<p><strong>B1:</strong> KNN analyzes the dataset by finding the k-nearest neighbors, based on a method like euclidean distance <strong>(GeeksforGeeks, nd)</strong>, and classifying a new data point based on the majority of those nearest neighbors. The expected outcome of this analysis is to identify customers who are likely to churn based on their similarities to other customers.</p>
<p><strong>B2:</strong> KNN assumes that data contained in the data set are in closes proximity to other data points that are similar <strong>(Towards Data Science, 2018)</strong>. In other words, similar customers have similar churn outcomes.</p>
<p><strong>B3:</strong> The following libraries were used to complete this analysis.</p>
<p><strong><em>Tidyverse</em></strong> was used for general data wrangling. I also used tidyverse for converting variables to other data types (factor, int, and numeric).</p>
<p><strong><em>Caret</em></strong> was maybe the most used library. It was used for tasks involved in training the model like <code>trainControl()</code> for cross validation, in this case a 10 fold cross validation that was repeated 3 times to evaluate the models performance. Further training was completed with the <code>train()</code> function. The train function in caret allowed me to find and select the best K value as well as to use “center” and “scale” to standardize the data. Caret allowed me to evaluate the models performance and make predictions. I was able to generate predictions for the test data with the <code>predict()</code> function within caret. Lastly, I was able to evaluate the models performance by creating a confusion matrix using <code>confusionMatrix()</code>. This function let me evaluate the sensitivity, specificity, accuracy, and several other measures.</p>
<p><strong><em>ROCR</em></strong> was used to evaluate and visualize the model’s performance by plotting the ROC curve and calculating the AUC. I used <code>prediction()</code> to create an object ‘<em>perf</em>’ to evaluate the model’s performance using the <code>performance()</code> function. The performance function allowed me to calculate the true positive and false positive rates, both of which are required for plotting the ROC curve. I used <code>plot()</code> to plot the model’s performance with a colorized line and a red dashed line, that represents a baseline where the model would be no better than random guessing. After this I calculated the AUC using the performance function again.</p>
</section>
<section id="part-iii-data-preparation" class="level1">
<h1><strong>Part III: Data Preparation</strong></h1>
<p><strong>C1:</strong> My data preparation goals were to ensure that the categorical variables were properly encoded as numeric values (0/1) <strong>(R is My Hammer, n.d., <em>Pre-Processing</em>)</strong>, and the quantitative variable <code>Tenure</code> is scaled appropriately so that KNN can accurately calculate distances. There are also some categorical variables that have multiple unique values that needed to be encoded into dummy variables. I did this using one-hot encoding.</p>
<p><strong>C2:</strong> In D208 Task 2 I had created a reduced logistic regression model using Akaike Information Criterion (AIC) and backward elimination. I chose to use those same variables from the reduced logistic regression model because they all had a statistically significant p-value. The selected variables are as follows:</p>
<p><strong>Categorical Variables:</strong></p>
<p><code>Churn</code> (Dependent variable), <code>Techie</code>, <code>Contract</code>, <code>InternetService</code>, <code>Phone</code>, <code>Multiple</code>, <code>OnlineBackup</code>, <code>DeviceProtection</code>, <code>StreamingTV</code>, <code>StreamingMovies</code> and, <code>PaymentMethod</code></p>
<p><strong>Quantitative variable:</strong></p>
<p><code>Tenure</code> (Numeric)</p>
<p><strong>C3:</strong> I began by removing all the variables that I was not going to use by selecting only the variables that were included in my reduced model in D208. To ensure the model interprets categorical variables correctly, I converted all binary categorical variables to factors with levels <code>0</code> and <code>1</code> for “No”, and “Yes.” Then I created dummy variables for the categorical variables that had multiple categories. Additionally, I ensured that <code>Tenure</code> is numeric because a tenure of 30 months should be more similar to 35 months than 10 months. Because of this it is essential that tenure is numeric. Lastly, I standardized the data because KNN is based on distance calculations and a large tenure could dominate the distance calculation. In my code below the standardization (z-score standardization), in which each of the variables have a mean of 0 and a standard deviation of 1 <strong>(Buya, 2023)</strong>, is accomplished with the line <code>churn$Tenure &lt;- as.numeric(scale(churn$Tenure))</code>. <code>Scale()</code> will return a matrix by default so I ensured that it is converted to numeric after scaling.</p>
<p><strong>C4:</strong> The cleaned data set will be included in my submission files and will be named <code>CLEANED_churn.csv</code>.</p>
</section>
<section id="part-iv-analysis" class="level1">
<h1><strong>Part IV: Analysis</strong></h1>
<p><strong>D1:</strong> I split the data into training and test data with an 80/20 split.</p>
<p><strong>D2:</strong>&nbsp;I used KNN to predict customer churn based on factors like <code>Techie</code>, <code>Contract</code>, <code>InternetService</code>, <code>Phone</code>, <code>Multiple</code>, <code>OnlineBackup</code>, <code>DeviceProtection</code>, <code>StreamingTV</code>, <code>StreamingMovies</code> and, <code>PaymentMethod</code>. To improve accuracy I applied cross validation with the <code>method="repeatedcv"</code>. This 10 fold cross validation process is repeated 3 times.</p>
<p>Before training, I standardized the quantitative variable using <code>churn$Tenure &lt;- as.numeric(scale(churn$Tenure))</code>. This ensures that this particular values does not dominate the distance measurements the KNN relies on because the other variables are all binary at this point. I used the <code>predict()</code> function to make predictions using new data stored in the training set.</p>
<p>To further evaluate the model I created a ROC curve, which shows how well the model distinguishes between customers who churn and those who do not. Along with the ROC, I also calculated the AUC to confirm the model’s performance.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="D209_Task1_V1_WriteUp_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>D3:</strong>&nbsp;The code used explained in section D2 is provided below.</p>
</section>
<section id="part-v-data-summary-and-implications" class="level1">
<h1><strong>Part V: Data Summary and Implications</strong></h1>
<p><strong>E1:</strong> AUC ranges from 0.5 - 1. Values close to 1 indicates that the model is accurately separating churned and non-churned customers. In this case, the AUC score is 0.9422046 meaning that the model has a strong ability to rank customers based on their likelihood of churning.</p>
<p><strong>E2.</strong> &nbsp;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   No  Yes
       No  1382  140
       Yes   99  365
                                          
               Accuracy : 0.8797          
                 95% CI : (0.8645, 0.8937)
    No Information Rate : 0.7457          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.674           
                                          
 Mcnemar's Test P-Value : 0.009671        
                                          
            Sensitivity : 0.9332          
            Specificity : 0.7228          
         Pos Pred Value : 0.9080          
         Neg Pred Value : 0.7866          
             Prevalence : 0.7457          
         Detection Rate : 0.6959          
   Detection Prevalence : 0.7664          
      Balanced Accuracy : 0.8280          
                                          
       'Positive' Class : No              
                                          </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "AUC : 0.943"</code></pre>
</div>
</div>
<p>This model has an accuracy of 87.97%, meaning that it can correctly predict the churn status of a custom the majority of the time. This models accuracy is better than the No Information Rate of 74.57%, meaning that it performs significantly better than if the model just predicted based on the majority class. The p-value of &lt; 2.2e-16 confirms that this model’s predictions are not due to random chance. The sensitivity rate of this model is 93.32%, meaning that the model is very good at identifying the true negatives, or the customers who did not churn. In contrast, 72.28% (specificity) of the time, the model correctly identified the true positives, the customers who did churn.</p>
<p>Despite the relatively low specificity, the model has balanced predictive values, meaning that in real world predictions this model does a good job correctly predicting the churn status of customers. When the model predicts a customer will not churn, it is correct 90.80% of the time (<code>Pos Pred Value</code>). Similarly, when the model predicts that a customer will churn, it is correct 78.66% of the time (<code>Neg Pred Value</code>).</p>
<p>Considering the accuracy rate of 87.97% and the AUC score of 0.9422046, I can conclude that in the majority of cases, this model will correctly predict or identify the churn status of a customer. Businesses can use this model to proactively target customers who are at risk for churn.</p>
<p><strong>E3.</strong>&nbsp;One limitation of this analysis is the use of mostly binary variables in the model. Since KNN works with distance measurements (euclidean distance in this case), it works best with continuous variables where the variables have a wider range of distance. But with Binary variables with only 1 or 0 as their values, the distances are shorter and lose precision. In this KNN model I have only one continuous variable, <code>Tenure</code>, and the rest are binary.</p>
<p><strong>E4.</strong> Based on the model’s performance, the organization should focus on proactive retention strategies for at-risk customers. With 87.97% and the AUC score of 0.9422046, the model effectively predicts churn, allowing the company to intervene early. Since it correctly identifies customers who churn 72.28% of the time, the company should use these insights to offer personalized discounts, improved support, or loyalty incentives to address the customers who are at risk of churning.</p>
</section>
<section id="part-vi-demonstration" class="level1">
<h1><strong>Part VI: Demonstration</strong></h1>
<p>F.&nbsp;My panopto video link will be provided in the submission files.<br>
</p>
<p><strong>Sources</strong></p>
<ol type="1">
<li><p><strong>Buya, A. (2023, July)</strong>. <em>The fundamentals of k-nearest neighbors: Normalization and standardization</em>. Medium. Retrieved from <a href="https://medium.com/@buyaalfariz/the-fundamentals-of-k-nearest-neighbors-normalization-and-standardization-a3e6ca616d57">https://medium.com/@buyaalfariz/the-fundamentals-of-k-nearest-neighbors-normalization-and-standardization-a3e6ca616d57</a></p></li>
<li><p><strong>Towards Data Science. (2018, September)</strong>. <em>Machine learning basics with the K-nearest neighbors algorithm</em>. Retrieved from https://towardsdatascience.com/machine-learning-basics-with-the-k-nearest-neighbors-algorithm-6a6e71d01761</p></li>
<li><p><strong>GeeksforGeeks. (n.d.)</strong>. <em>K-nearest neighbours</em>. Retrieved from <a href="https://www.geeksforgeeks.org/k-nearest-neighbours/#" class="uri">https://www.geeksforgeeks.org/k-nearest-neighbours/#</a></p></li>
<li><p><strong>R is My Hammer. (n.d.)</strong>. <em>Pre-processing in machine learning</em>. Retrieved from <a href="http://rismyhammer.com/ml/Pre-Processing.html" class="uri">http://rismyhammer.com/ml/Pre-Processing.html</a></p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>