<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tyson Biegler">

<title>D208 Task 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="WriteUpV1_T2_files/libs/clipboard/clipboard.min.js"></script>
<script src="WriteUpV1_T2_files/libs/quarto-html/quarto.js"></script>
<script src="WriteUpV1_T2_files/libs/quarto-html/popper.min.js"></script>
<script src="WriteUpV1_T2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="WriteUpV1_T2_files/libs/quarto-html/anchor.min.js"></script>
<link href="WriteUpV1_T2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="WriteUpV1_T2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="WriteUpV1_T2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="WriteUpV1_T2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="WriteUpV1_T2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">D208 Task 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tyson Biegler </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="part-i-research-question" class="level2">
<h2 class="anchored" data-anchor-id="part-i-research-question"><strong>Part I: Research Question</strong></h2>
<p><strong>A1.</strong>&nbsp;&nbsp;What variables have the biggest impact on customer churn?</p>
<p><strong>A2.</strong>&nbsp;this analysis aims to create a multiple logistic regression model that can accurately predict customer churn. Company executives can use the data from this model to address customer churn more accurately.</p>
</section>
<section id="part-ii-method-justification" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-method-justification"><strong>Part II: Method Justification</strong></h2>
<p><strong>B1</strong>.&nbsp;&nbsp;According to Zach Bobbitt from statology.org, there are 6 Assumptions of logistic regression. <strong>(Z. Bobbit 2020)</strong><br>
</p>
<ol type="1">
<li><p>The Response variable needs to be binary. I will be using a binary factor type in this analysis.</p></li>
<li><p>The observations need to be independent because they do not represent the same individual. For example, time series data about the height of an individual would violate this assumption because the observations are all repeated measurements unique to an individual.</p></li>
<li><p>multi-colinearity needs to be minimized among variables. Multicolinearity occurs when there is a high correlation between variables. Multi-colinearity is a problem because the highly correlated variables essentially tell the same story and do not add any unique information.</p></li>
<li><p>Outliers have been appropriately managed.</p></li>
<li><p>The relationship between the explanatory variables and the logit of the response variable is linear.</p></li>
<li><p>Lastly, linear regression assumes that the sample size is large enough to ensure reliable and meaningful conclusions from the fitted model.</p></li>
</ol>
<p><strong>B2</strong>.&nbsp; I will be using R within R-Studio to perform this analysis. While Python can perform this same statistical analysis, it was not explicitly designed for this purpose. R, on the other hand, was specifically designed for statistical analysis (<strong>Ihaka, n.d., p.&nbsp;12</strong>). Due to this, R is the more logical choice for performing statistical tasks. Secondly, I have more experience using R than I do with Python. I’ve used R to complete previous courses, and I feel that it is more intuitive than Python.</p>
<p><strong>B3</strong>.&nbsp;&nbsp;Logistic regression is the appropriate technique for this analysis because the dependent variable is binary (Yes = 1, No = 0). Additionally, the predictor variables include a mix of categorical and continuous types, making logistic regression a good choice. Lastly, logistic regression ranks customers based on their odds of churning, enabling the company to promptly identify and address at-risk customers.</p>
</section>
<section id="part-iii-data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="part-iii-data-preparation"><strong>Part III: Data Preparation</strong></h2>
<p><strong>C1</strong>. I need to remove irrelevant columns such as <code>customer_id</code>, <code>CaseOrder</code>, and some other columns that have data not relevant to my question. Secondly I have to update the data types. The Categorical variables will be converted to factors and the remaining quantitative variables will be converted to integer or numeric depending on the values. Once I have all the data cleaned and prepared Ill be ready to feed it into an initial linear model.</p>
<p><strong>C2</strong>. The dependent variable I’m explaining is ‘<code>Churn</code>.’ After I removed several columns of data that had to many unique entries or contained irrelevant information, such as <code>customer_id</code>, or <code>lat</code> and <code>lng</code>, I was left with around 70 independent variables, including the automatically generated dummy variables. The numeric and integer types all include a min, 1st Qu, Median, Mean, 3rd Qu, and Max values whereas the factors include just the count for each level. The summary statistics below show all of the variables including the dependant variable, that I will be using in my linear model. I will explain how I ended up with these variables in the next few sections.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(churn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Population           Area         Children           Age       
 Min.   :     0   Rural   :3327   Min.   : 0.000   Min.   :18.00  
 1st Qu.:   738   Suburban:3346   1st Qu.: 0.000   1st Qu.:35.00  
 Median :  2910   Urban   :3327   Median : 1.000   Median :53.00  
 Mean   :  9757                   Mean   : 2.088   Mean   :53.08  
 3rd Qu.: 13168                   3rd Qu.: 3.000   3rd Qu.:71.00  
 Max.   :111850                   Max.   :10.000   Max.   :89.00  
                                                                  
     Income                  Marital           Gender     Churn   
 Min.   :   348.7   Divorced     :2092   Female   :5025   0:7350  
 1st Qu.: 19224.7   Married      :1911   Male     :4744   1:2650  
 Median : 33170.6   Never Married:1956   Nonbinary: 231           
 Mean   : 39806.9   Separated    :2014                            
 3rd Qu.: 53246.2   Widowed      :2027                            
 Max.   :258900.7                                                 
                                                                  
 Outage_sec_perweek     Email          Contacts      Yearly_equip_failure
 Min.   : 0.09975   Min.   : 1.00   Min.   :0.0000   Min.   :0.000       
 1st Qu.: 8.01821   1st Qu.:10.00   1st Qu.:0.0000   1st Qu.:0.000       
 Median :10.01856   Median :12.00   Median :1.0000   Median :0.000       
 Mean   :10.00185   Mean   :12.02   Mean   :0.9942   Mean   :0.398       
 3rd Qu.:11.96949   3rd Qu.:14.00   3rd Qu.:2.0000   3rd Qu.:1.000       
 Max.   :21.20723   Max.   :23.00   Max.   :7.0000   Max.   :6.000       
                                                                         
 Techie             Contract    Port_modem Tablet      InternetService Phone   
 0:8321   Month-to-month:5456   0:5166     0:7009   DSL        :3463   0: 933  
 1:1679   One year      :2102   1:4834     1:2991   Fiber Optic:4408   1:9067  
          Two Year      :2442                       None       :2129           
                                                                               
                                                                               
                                                                               
                                                                               
 Multiple OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV
 0:5392   0:6424         0:5494       0:5614           0:6250      0:5071     
 1:4608   1:3576         1:4506       1:4386           1:3750      1:4929     
                                                                              
                                                                              
                                                                              
                                                                              
                                                                              
 StreamingMovies PaperlessBilling                  PaymentMethod 
 0:5110          0:4118           Bank Transfer(automatic):2229  
 1:4890          1:5882           Credit Card (automatic) :2083  
                                  Electronic Check        :3398  
                                  Mailed Check            :2290  
                                                                 
                                                                 
                                                                 
     Tenure       MonthlyCharge    Bandwidth_GB_Year Timely_response
 Min.   : 1.000   Min.   : 79.98   Min.   : 155.5    1: 224         
 1st Qu.: 7.918   1st Qu.:139.98   1st Qu.:1236.5    2:1393         
 Median :35.431   Median :167.48   Median :3279.5    3:3448         
 Mean   :34.526   Mean   :172.62   Mean   :3392.3    4:3358         
 3rd Qu.:61.480   3rd Qu.:200.73   3rd Qu.:5586.1    5:1359         
 Max.   :71.999   Max.   :290.16   Max.   :7159.0    6: 199         
                                                     7:  19         
 Timely_fixes Timely_replacements Reliability Options    Respectful   Courteous
 1: 217       3      :3435        1: 221      1: 206   3      :3445   1: 219   
 2:1360       4      :3410        2:1350      2:1378   4      :3333   2:1309   
 3:3415       2      :1424        3:3430      3:3462   2      :1427   3:3446   
 4:3412       5      :1313        4:3452      4:3417   5      :1382   4:3456   
 5:1368       6      : 203        5:1335      5:1321   6      : 210   5:1335   
 6: 215       1      : 202        6: 203      6: 204   1      : 190   6: 224   
 7:  13       (Other):  13        7:   9      7:  12   (Other):  13   7:  11   
 Active_listening
 3      :3461    
 4      :3400    
 2      :1378    
 5      :1335    
 1      : 206    
 6      : 205    
 (Other):  15    </code></pre>
</div>
</div>
<p><strong>C3</strong>.&nbsp; After running stepwise model selection based on the Akaike Information Criterion (AIC) and Backward elimination, I was left with far fewer variables than the initial model that included nearly 50 variables. I eliminated more using <code>VIF()</code>, which I will explain later. The following charts are the distributions of the variables I included in the final “reduced_model.”</p>
</section>
<section id="go-over-these-plots-to-make-sure-im-still-using-these-variables" class="level1">
<h1>GO OVER THESE PLOTS TO MAKE SURE IM STILL USING THESE VARIABLES</h1>
<p><strong>Univariate plots</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WriteUpV1_T2_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WriteUpV1_T2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Bivariate plots</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WriteUpV1_T2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WriteUpV1_T2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>C4</strong>.&nbsp;renamed the survey response variables to improve clarity and converted them to factors. R automatically generates dummy variables for each unique value in these factor variables. Additionally, I applied scaling to some of the larger quantitative variables using the built-in <code>scale()</code> function in R <strong>(R Core Team, 2019)</strong>. This process, known as standardization or z-score normalization, is described in an article from GeeksforGeeks titled ’<em>Logistic Regression and the Feature Scaling Ensemble.</em></p>
<p><strong>C5</strong>.&nbsp;The prepared data set will be included in my submission files.<br>
&nbsp;</p>
<section id="part-iv-model-comparison-and-analysis" class="level2">
<h2 class="anchored" data-anchor-id="part-iv-model-comparison-and-analysis"><strong>Part IV: Model Comparison and Analysis</strong></h2>
<p><em>Note: Your responses to the task prompts must be provided in a document file. Unless otherwise specified, responses to PA requirements that are included in a Python or RStudio notebook will not be accepted.</em></p>
<p><strong>D1.</strong></p>
<p>To set up my initial model i first started by seperateing in the data in to training and test sets with a 80/20 split. The initial model will attempt to explain <code>Churn</code> by all the remaining variables in the dataset that were not removed in the data cleaning step.<br>
<br>
I begin by creating a linear model using <code>glm()</code> because I need to use the statistical family “binomial’ for logistic regression. I based the model on the training set of data, <code>churn_train</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>initial_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Churn <span class="sc">~</span>. , <span class="at">data =</span> churn_train, <span class="at">family =</span> <span class="st">'binomial'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(initial_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Churn ~ ., family = "binomial", data = churn_train)

Coefficients:
                                       Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                          -4.839e+00  1.848e+00  -2.618 0.008834 ** 
Population                            3.367e-07  3.133e-06   0.107 0.914436    
AreaSuburban                         -4.461e-02  1.086e-01  -0.411 0.681180    
AreaUrban                             4.823e-02  1.074e-01   0.449 0.653253    
Children                              6.610e-02  1.564e-01   0.423 0.672563    
Age                                  -7.418e-03  1.673e-02  -0.443 0.657468    
Income                                2.676e-07  1.535e-06   0.174 0.861637    
MaritalMarried                        2.851e-01  1.394e-01   2.046 0.040747 *  
MaritalNever Married                  4.174e-02  1.382e-01   0.302 0.762705    
MaritalSeparated                      2.351e-01  1.370e-01   1.716 0.086140 .  
MaritalWidowed                        2.577e-01  1.374e-01   1.876 0.060653 .  
GenderMale                            4.493e-01  3.270e-01   1.374 0.169451    
GenderNonbinary                      -1.930e-01  3.197e-01  -0.604 0.546060    
Outage_sec_perweek                   -1.501e-02  1.479e-02  -1.015 0.310187    
Email                                -7.513e-03  1.453e-02  -0.517 0.605060    
Contacts                              5.559e-02  4.462e-02   1.246 0.212784    
Yearly_equip_failure                 -1.971e-02  6.871e-02  -0.287 0.774245    
Techie1                               1.079e+00  1.169e-01   9.231  &lt; 2e-16 ***
ContractOne year                     -3.501e+00  1.470e-01 -23.824  &lt; 2e-16 ***
ContractTwo Year                     -3.576e+00  1.453e-01 -24.617  &lt; 2e-16 ***
Port_modem1                           1.054e-01  8.794e-02   1.198 0.230864    
Tablet1                              -2.674e-02  9.628e-02  -0.278 0.781216    
InternetServiceFiber Optic           -3.156e+00  2.391e+00  -1.320 0.186877    
InternetServiceNone                  -1.870e+00  1.905e+00  -0.981 0.326376    
Phone1                               -2.455e-01  1.481e-01  -1.657 0.097435 .  
Multiple1                             3.464e-01  2.306e-01   1.502 0.133129    
OnlineSecurity1                      -8.797e-02  3.552e-01  -0.248 0.804404    
OnlineBackup1                        -3.286e-02  2.067e-01  -0.159 0.873648    
DeviceProtection1                    -5.610e-04  2.660e-01  -0.002 0.998317    
TechSupport1                         -2.094e-01  1.978e-01  -1.059 0.289743    
StreamingTV1                          1.471e+00  5.793e-01   2.539 0.011129 *  
StreamingMovies1                      1.556e+00  4.152e-01   3.748 0.000178 ***
PaperlessBilling1                     1.434e-01  8.901e-02   1.611 0.107245    
PaymentMethodCredit Card (automatic)  1.486e-01  1.321e-01   1.125 0.260675    
PaymentMethodElectronic Check         5.920e-01  1.202e-01   4.925 8.42e-07 ***
PaymentMethodMailed Check             1.179e-01  1.316e-01   0.896 0.370373    
Tenure                                4.758e-02  4.137e-01   0.115 0.908436    
MonthlyCharge                         4.630e-02  1.582e-02   2.927 0.003424 ** 
Bandwidth_GB_Year                    -2.017e-03  5.049e-03  -0.399 0.689543    
Timely_response2                      1.056e-01  3.418e-01   0.309 0.757296    
Timely_response3                     -7.566e-02  3.429e-01  -0.221 0.825370    
Timely_response4                     -1.076e-01  3.558e-01  -0.302 0.762311    
Timely_response5                     -1.304e-01  3.795e-01  -0.344 0.731096    
Timely_response6                      3.060e-02  4.868e-01   0.063 0.949869    
Timely_response7                      1.409e+00  1.348e+00   1.046 0.295702    
Timely_fixes2                         2.154e-01  3.684e-01   0.585 0.558843    
Timely_fixes3                         1.219e-01  3.690e-01   0.330 0.741147    
Timely_fixes4                         1.855e-01  3.776e-01   0.491 0.623126    
Timely_fixes5                         2.166e-02  3.981e-01   0.054 0.956611    
Timely_fixes6                         2.053e-01  5.007e-01   0.410 0.681806    
Timely_fixes7                        -6.657e-01  7.369e+00  -0.090 0.928015    
Timely_replacements2                 -3.269e-01  3.419e-01  -0.956 0.339021    
Timely_replacements3                 -2.369e-01  3.372e-01  -0.703 0.482339    
Timely_replacements4                 -3.094e-01  3.427e-01  -0.903 0.366706    
Timely_replacements5                 -1.997e-01  3.624e-01  -0.551 0.581665    
Timely_replacements6                  2.301e-01  4.835e-01   0.476 0.634229    
Timely_replacements7                 -1.537e+00  1.295e+00  -1.187 0.235277    
Timely_replacements8                 -1.541e+01  8.828e+02  -0.017 0.986073    
Reliability2                          1.696e-01  3.041e-01   0.558 0.577032    
Reliability3                         -1.634e-01  2.934e-01  -0.557 0.577510    
Reliability4                         -5.346e-02  2.969e-01  -0.180 0.857110    
Reliability5                         -9.182e-03  3.150e-01  -0.029 0.976749    
Reliability6                          1.445e-01  4.290e-01   0.337 0.736239    
Reliability7                         -1.380e+01  3.028e+02  -0.046 0.963658    
Options2                             -3.150e-02  3.517e-01  -0.090 0.928640    
Options3                             -1.678e-01  3.446e-01  -0.487 0.626236    
Options4                             -6.010e-02  3.494e-01  -0.172 0.863411    
Options5                              3.204e-02  3.681e-01   0.087 0.930649    
Options6                             -4.349e-02  4.570e-01  -0.095 0.924184    
Options7                             -2.083e+00  1.313e+00  -1.586 0.112741    
Respectful2                           4.614e-01  3.685e-01   1.252 0.210514    
Respectful3                           4.663e-01  3.620e-01   1.288 0.197807    
Respectful4                           5.603e-01  3.685e-01   1.520 0.128396    
Respectful5                           4.490e-01  3.859e-01   1.163 0.244701    
Respectful6                           2.759e-01  4.680e-01   0.589 0.555546    
Respectful7                           6.015e-01  4.381e+00   0.137 0.890787    
Respectful8                          -1.455e+01  8.827e+02  -0.016 0.986851    
Courteous2                            2.446e-01  3.204e-01   0.763 0.445181    
Courteous3                            3.610e-01  3.078e-01   1.173 0.240947    
Courteous4                            2.223e-01  3.124e-01   0.711 0.476849    
Courteous5                            4.118e-01  3.331e-01   1.236 0.216366    
Courteous6                            4.166e-01  4.387e-01   0.950 0.342299    
Courteous7                           -7.384e-01  2.013e+00  -0.367 0.713830    
Active_listening2                    -9.349e-02  3.068e-01  -0.305 0.760544    
Active_listening3                    -1.828e-02  2.925e-01  -0.062 0.950170    
Active_listening4                    -1.316e-01  2.952e-01  -0.446 0.655651    
Active_listening5                     6.247e-03  3.122e-01   0.020 0.984035    
Active_listening6                     3.980e-02  4.201e-01   0.095 0.924522    
Active_listening7                    -5.120e-01  1.045e+00  -0.490 0.624126    
Active_listening8                    -1.401e+01  8.827e+02  -0.016 0.987333    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9251.6  on 7999  degrees of freedom
Residual deviance: 3419.4  on 7910  degrees of freedom
AIC: 3599.4

Number of Fisher Scoring iterations: 13</code></pre>
</div>
</div>
<p>The summary of the initial model shows that there are several variables who’s coefficients do not add any statistically significant information to the model. I’ll address these in the next step.</p>
<p>The null deviance is 9251.6 on 7999 degrees of freedom, meaning that my response variable, <code>Churn</code>, shows a lot of variability without predictors and could be explained by adding predictor variables. The residual deviance of 3419.4 on 7910 degrees of freedom indicates that the predictor variables do indeed provide an effective explanation of the variability in <code>Churn</code>.</p>
<p>The AIC for this model is 3599.4. I will reference this number again when comparing the reduced model.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WriteUpV1_T2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>2.&nbsp;I’ve chosen to use backward stepwise selection <strong>(Larose &amp; Larose, 2019)</strong>, because I have a large amount of variables and backward elimination will remove each insignificant variable until only those values that have a meaningful contribution will remain.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>initial_model <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(<span class="at">object =</span> initial_model, <span class="at">direction =</span> <span class="st">"backward"</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(initial_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Churn ~ Children + Age + Techie + Contract + InternetService + 
    Phone + Multiple + OnlineSecurity + OnlineBackup + DeviceProtection + 
    StreamingTV + StreamingMovies + PaperlessBilling + PaymentMethod + 
    Tenure + MonthlyCharge + Bandwidth_GB_Year, family = "binomial", 
    data = churn_train)

Coefficients:
                                      Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                          -6.546167   0.670910  -9.757  &lt; 2e-16 ***
Children                             -0.146373   0.042548  -3.440 0.000581 ***
Age                                   0.015510   0.004485   3.458 0.000543 ***
Techie1                               1.099979   0.115276   9.542  &lt; 2e-16 ***
ContractOne year                     -3.445299   0.144164 -23.898  &lt; 2e-16 ***
ContractTwo Year                     -3.507074   0.141909 -24.714  &lt; 2e-16 ***
InternetServiceFiber Optic            0.095929   0.562920   0.170 0.864686    
InternetServiceNone                   0.761809   0.489279   1.557 0.119470    
Phone1                               -0.243791   0.145357  -1.677 0.093506 .  
Multiple1                             0.463706   0.161808   2.866 0.004160 ** 
OnlineSecurity1                      -0.564547   0.125614  -4.494 6.98e-06 ***
OnlineBackup1                        -0.249549   0.139805  -1.785 0.074265 .  
DeviceProtection1                    -0.337493   0.124476  -2.711 0.006702 ** 
StreamingTV1                          0.710337   0.267354   2.657 0.007886 ** 
StreamingMovies1                      1.097328   0.272227   4.031 5.56e-05 ***
PaperlessBilling1                     0.149497   0.087666   1.705 0.088140 .  
PaymentMethodCredit Card (automatic)  0.147691   0.130322   1.133 0.257100    
PaymentMethodElectronic Check         0.564349   0.118028   4.781 1.74e-06 ***
PaymentMethodMailed Check             0.102746   0.129278   0.795 0.426747    
Tenure                               -0.512633   0.099884  -5.132 2.86e-07 ***
MonthlyCharge                         0.026319   0.004895   5.377 7.59e-08 ***
Bandwidth_GB_Year                     0.004843   0.001214   3.988 6.65e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 9251.6  on 7999  degrees of freedom
Residual deviance: 3473.4  on 7978  degrees of freedom
AIC: 3517.4

Number of Fisher Scoring iterations: 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>)) <span class="co"># Arrange plots in a 2x2 grid</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(initial_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WriteUpV1_T2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>3.&nbsp;&nbsp;Provide a reduced logistic regression model that follows the feature selection or model evaluation process in part D2, including a screenshot of the output for <em>each</em> model.<br>
&nbsp;</p>
<p>E.&nbsp;&nbsp;Analyze the data set using your reduced logistic regression model by doing the following in a document file:</p>
<p>1.&nbsp;&nbsp;Explain your data analysis process by comparing the initial logistic regression model and reduced logistic regression model, including the following element:</p>
<p>•&nbsp;&nbsp;a model evaluation metric</p>
<p>2.&nbsp;&nbsp;Provide the output and <em>all</em> calculations of the analysis you performed, including the following elements for your reduced logistic regression model:</p>
<p>•&nbsp;&nbsp;confusion matrix</p>
<p>•&nbsp;&nbsp;accuracy calculation</p>
<p>3.&nbsp;&nbsp;Provide an executable, error-free copy of the code used to support the implementation of the logistic regression models using a Python or R file.<br>
&nbsp;</p>
</section>
<section id="part-v-data-summary-and-implications" class="level2">
<h2 class="anchored" data-anchor-id="part-v-data-summary-and-implications"><strong>Part V: Data Summary and Implications</strong></h2>
<p><em>Note: Your responses to the task prompts must be provided in a document file. Unless otherwise specified, responses to PA requirements that are included in a Python or RStudio notebook will not be accepted.</em><br>
&nbsp;</p>
<p>F.&nbsp;&nbsp;Summarize your findings and assumptions by doing the following in a document file:</p>
<p>1.&nbsp;&nbsp;Discuss the results of your data analysis, including the following elements:</p>
<p>•&nbsp;&nbsp;a regression equation for the reduced model</p>
<p>•&nbsp;&nbsp;an interpretation of the coefficients of the reduced model</p>
<p>•&nbsp;&nbsp;the statistical and practical significance of the reduced model</p>
<p>•&nbsp;&nbsp;the limitations of the data analysis</p>
<p>2.&nbsp;&nbsp;Recommend a course of action based on your results.<br>
&nbsp;</p>
</section>
<section id="part-vi-demonstration" class="level2">
<h2 class="anchored" data-anchor-id="part-vi-demonstration"><strong>Part VI: Demonstration</strong></h2>
<p>G.&nbsp;&nbsp;Provide a Panopto video recording that includes the presenter and a vocalized demonstration of the functionality of the code used for the analysis of the programming environment, including the following elements:</p>
<p>•&nbsp;&nbsp;an identification of the version of the programming environment</p>
<p>•&nbsp;&nbsp;a comparison of the initial logistic regression model you used and the reduced logistic regression model you used in your analysis</p>
<p>•&nbsp;&nbsp;an interpretation of the coefficients of the reduced model<br>
&nbsp;</p>
<p><em>Note: The audiovisual recording should feature you visibly presenting the material (i.e., not in voiceover or embedded video) and should simultaneously capture both you and your multimedia presentation.<br>
<br>
&nbsp;Note: For instructions on how to access and use Panopto, use the “Panopto How-To Videos” web link provided below. To access Panopto’s website, navigate to the web link titled “Panopto Access,” and then choose to log in using the “WGU” option. If prompted, log in using your WGU student portal credentials, and then it will forward you to Panopto’s website.<br>
<br>
&nbsp;To submit your recording, upload it to the Panopto drop box titled “Regression Modeling – NBMx | D208.” Once the recording has been uploaded and processed in Panopto’s system, retrieve the URL of the recording from Panopto and copy and paste it into the Links option. Upload the remaining task requirements using the Attachments option.</em><br>
&nbsp;</p>
<p>H.&nbsp;&nbsp;List the web sources used to acquire data or segments of third-party code to support the application. Ensure the web sources are reliable.<br>
&nbsp;</p>
<p>I.&nbsp;&nbsp;Acknowledge sources, using in-text citations and references, for content that is quoted, paraphrased, or summarized.</p>
<ol type="1">
<li><p><strong>Bobbitt, Z.</strong> (2020, October 13).The 6 Assumptions of Logistic Regression (With Examples). Statology. Retrieved December 29, 2024, from https://www.statology.org/assumptions-of-logistic-regression/)</p></li>
<li><p><strong>GeeksforGeeks.</strong> (2021, June 17). <em>Logistic Regression and the Feature Scaling Ensemble</em>. GeeksforGeeks. Retrieved January 2, 2025, from https://www.geeksforgeeks.org/logistic-regression-and-the-feature-scaling-ensemble/#</p></li>
<li><p><strong>Ihaka, R. (n.d.).</strong> The R Project: A brief history and thoughts about the future (p.&nbsp;12). The University of Auckland. Retrieved November 17, 2024, from https://www.stat.auckland.ac.nz/~ihaka/downloads/Otago.pdf (https://www.stat.auckland.ac.nz/~ihaka/downloads/Otago.pdf)</p></li>
<li><p><strong>Larose, C. D., &amp; Larose, D. T. (2019)</strong>. Data science using Python and R. Wiley. Retrieved from https://eds.p.ebscohost.com/eds/ebookviewer/ebook/bmxlYmtfXzIwOTEzNzFfX0FO0?sid=04ef9475-3bed 4dbe-8317-a1c5eb6da3cb@redis&amp;vid=0&amp;format=EB&amp;lpid=lp_151&amp;rid=0</p></li>
<li><p><strong>R Core Team.</strong> (2019). <em>scale</em> function. <em>R Documentation</em>. Retrieved January 1, 2025 from https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/scale<br>
&nbsp;</p></li>
</ol>
<p>J.&nbsp;&nbsp;Demonstrate professional communication in the content and presentation of your submission.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>